##
# This file is part of the IVMS Online.
#
# @copyright 2023 - 2024 © by Rafał Wrzeszcz - Wrzasq.pl.
##

on:
    push:
        tags-ignore: "**"
        branches:
            - "master"
    pull_request:
        branches: "**"
    schedule:
        -
            cron: "0 3 * * 0"

jobs:
    build:
        uses: "ivms-online/.github/.github/workflows/rust-build.yaml@2b6f20a6661cfd0f125851504817920cc31bf3ce"
        secrets: "inherit"
